### ISSUE TITLE
Improve LLVM CMake detection

### ISSUE THREAD

**Issue by xdek42** [jcowgill/lcool#1]
Hello, Sorry for bothering you. I'm a LLVM beginner. I found your project lcool in github which is really cool and I want to learn llvm by reading your code. But I have a problem when I build lcool. My llvm version is LLVM_3.50svn

When I run "cmake ..", It generates an error: Could NOT find LLVM (missing: LLVM_LIBRARIES). I found the code you write in FindLLVM.cmake:

   find_library(
        LLVM_LIBRARIES
        "LLVM-${LLVM_VERSION}"
        PATHS "${LLVM_LIBRARY_DIRS}")

I have no library named "LLVM-3.50svn" in /usr/local/lib(LLVM_LIBRARY_DIRS), so i changed "LLVM-${LLVM_VERSION}" to  NAMES "LLVMCore" "LLVMSupport", then it can generate makefile, but when i run make, It will still generate link error, such as "undefined reference to `llvm::Module::getTypeByName(llvm::StringRef) const'". 

So how should I modify the FindLLVM.cmake in order to  build the lcool successfully?

Thanks.

**Comment by jcowgill** [comment]
Hi!

Just so you know, this project isn't finished - there's still some work to do on the backend parts. Most of the TODOs are marked with C++ `#warning` directives. One day I may get around to it :)

The `FindLLVM.cmake` file was written with shared libraries in mind (like on Debian) and I never tested it elsewhere. If you're using static libraries, you should just include everything and the linker will discard stuff it doesn't need. You could try using the output of `llvm-config --libfiles` as the value of `LLVM_LIBRARIES`.

On another note, one major issue is that `src/lcool_runtime.ll` is tied to a particular LLVM version (3.5 in this case). I'll have to think about the best way to solve that. Possibly rewriting it in C and using `clang -emit-llvm` at build time is the best way to go.

James

**Comment by xdek42** [comment]
Thank you for your help，I successfully compiled lcool by hand : 
`clang++ *.cpp`llvm-config --cxxflags --ldflags --system-libs --libs`-lboost_program_options  -o lcool`
Now, Through reading your code，I can learn to build my own backend for my cool compiler.
Thanks again, Have a nice day :)

**Comment by jcowgill** [comment]
Great! I think probably the LLVM detection could do with improving so I'll leave this bug open in case I get around to fixing it. I can't make any promises though.

**Comment by jcowgill** [comment]
Hopefully that works better.
